In [3]:
# Importing libraries
import numpy as np
import pandas as pd

# Exercise 1 
arr1 = np.arange(1, 11)
reshaped_arr1 = arr1.reshape(2, 5)
print("Reshaped array:\n", reshaped_arr1)

Reshaped array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
# Exercise 2 
arr2 = np.arange(1, 21)
extracted = arr2[5:16]
print("Extracted elements:\n", extracted)

Extracted elements:
 [ 6  7  8  9 10 11 12 13 14 15 16]


In [8]:
# Exercise 3 
data = {'apples': 3, 'bananas': 2, 'oranges': 1}
fruits = pd.Series(data)
fruits['pears'] = 4
print("Updated Series:\n",fruits)

Updated Series:
 apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [9]:
# Exercise 4 
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Helen', 'Ivy', 'John'],
    'age': [25, 32, 28, 45, 35, 29, 41, 33, 26, 30],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'F', 'M']
}
df = pd.DataFrame(data)
print("DataFrame:\n", df)

DataFrame:
       name  age gender
0    Alice   25      F
1      Bob   32      M
2  Charlie   28      M
3    David   45      M
4      Eva   35      F
5    Frank   29      M
6    Grace   41      F
7    Helen   33      F
8      Ivy   26      F
9     John   30      M


In [10]:
# Exercise 5 
occupations = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager',
               'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
df['occupation'] = occupations
print("DataFrame with occupation:\n", df)

DataFrame with occupation:
       name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   32      M     Manager
2  Charlie   28      M     Analyst
3    David   45      M  Programmer
4      Eva   35      F     Manager
5    Frank   29      M     Analyst
6    Grace   41      F  Programmer
7    Helen   33      F     Manager
8      Ivy   26      F     Analyst
9     John   30      M  Programmer


In [ ]:
# Exercise 6 
age_filtered_df = df[df['age'] >= 30]
print("\nExercise 6 - Rows with age >= 30:\n", age_filtered_df)

In [ ]:
# Exercise 7 
df.to_csv('people.csv', index=False)
df_from_csv = pd.read_csv('people.csv')
print("\nExercise 7 - Data read from CSV:\n", df_from_csv)